trigger:
  - main

pool:
  name: LocalAgentPool

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: npm run build
    displayName: 'npm run build'

  # Agrega aquí los pasos de SonarCloud si los necesitas
  # - task: SonarCloudPrepare@1
  #   ...
  # - task: SonarCloudAnalyze@1
  #   ...
  # - task: SonarCloudPublish@1
  #   ...
