trigger:
  - main

pool:
  name: LocalAgentPool

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'azure-devops'
      organization: 'jherreraj'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'jherreraj_Sistema-de-Gestión-de-Proyectos-Agiles'
      cliProjectName: 'Sistema de Gestión de Proyectos Agiles'

  - script: npm run build
    displayName: 'npm run build'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
